"""Build the WeChat mini-program data bundle: compressed photos + data.js.

Reuses the same inputs as build_app.py but emits:
  miniprogram/images/<id>.jpg   300px q60 (main package must stay under 2MB)
  miniprogram/data.js           module.exports = { DISHES, ING, PRICES, REST }

Run after any data refresh, then open miniprogram/ in WeChat DevTools.
"""
import io
import json
import os
import sys

from PIL import Image

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MP = os.path.join(ROOT, "miniprogram")
# tiers tried in order until the bundle fits the 2MB main-package budget
TIERS = [(300, 60), (250, 55), (220, 50)]


def load(rel, default=None):
    p = os.path.join(ROOT, rel)
    if not os.path.exists(p):
        if default is not None:
            return default
        sys.exit(f"missing {rel}")
    return json.load(open(p, encoding="utf-8"))


result = load("data/workflow_result.json")
tags = {d["name"]: d for d in load("data/dish_tags.json")["dishes"]}
album_tags = {d["name"]: d for d in load("data/album_tags.json", {"dishes": []})["dishes"]}
DEFAULT_ALBUM = {"meal": "副菜", "cat": ["蛋白"], "meat": [], "spice": 0, "cuisine": "家常", "flags": []}

import shutil

img_dir = os.path.join(MP, "images")
shutil.rmtree(img_dir, ignore_errors=True)


def build_images(max_edge, quality):
    os.makedirs(img_dir, exist_ok=True)
    total = 0
    dishes = []
    for d in result["dishes"]:
        name = d["name"]
        t = tags.get(name) or album_tags.get(name) or {**DEFAULT_ALBUM, "name": name}
        img = None
        best = d.get("best")
        if best:
            pid = best.split(".")[0]
            for sub in ("crops", "m_thumbs", "thumbs"):
                src = os.path.join(ROOT, sub, pid + ".jpg")
                if os.path.exists(src):
                    im = Image.open(src).convert("RGB")
                    im.thumbnail((max_edge, max_edge))
                    dst = os.path.join(img_dir, pid + ".jpg")
                    im.save(dst, "JPEG", quality=quality, optimize=True, progressive=True)
                    total += os.path.getsize(dst)
                    img = f"/images/{pid}.jpg"
                    break
        dishes.append({
            "name": name, "meal": t["meal"], "cat": t["cat"], "meat": t["meat"],
            "spice": t["spice"], "cui": t["cuisine"], "flags": t["flags"],
            "src": d["source"], "count": d.get("photoCount", 0), "img": img,
        })
    order = {"早饭": 0, "主菜": 1, "副菜": 2}
    dishes.sort(key=lambda x: (order.get(x["meal"], 3), x["src"] != "list", -x["count"]))
    return dishes, total


for max_edge, quality in TIERS:
    dishes, img_bytes = build_images(max_edge, quality)
    if img_bytes / 1024 < 1500:
        print(f"tier {max_edge}px q{quality}: images fit ({img_bytes/1024:.0f} KB)")
        break
    print(f"tier {max_edge}px q{quality}: {img_bytes/1024:.0f} KB too big, trying next tier")

ing = {d["name"]: d["ingredients"] for d in load("data/ingredients.json")["dishes"]}

prices_raw = load("data/prices.json", {})
prices = {}
for shop, terms in prices_raw.items():
    keep = {}
    for term, rec in terms.items():
        prods = rec.get("products") or []
        if prods:
            keep[term] = {"name": prods[0]["name"], "price": prods[0]["price"]}
            if rec.get("source"):
                keep[term]["src"] = rec["source"]
    prices[shop] = keep

rest = load("data/restaurants.json", None)

payload = (
    "// generated by scripts/build_miniprogram.py — do not edit\n"
    f"module.exports = {{\n"
    f"DISHES: {json.dumps(dishes, ensure_ascii=False, separators=(',', ':'))},\n"
    f"ING: {json.dumps(ing, ensure_ascii=False, separators=(',', ':'))},\n"
    f"PRICES: {json.dumps(prices, ensure_ascii=False, separators=(',', ':'))},\n"
    f"REST: {json.dumps(rest, ensure_ascii=False, separators=(',', ':'))}\n"
    f"}};\n"
)
open(os.path.join(MP, "data.js"), "w", encoding="utf-8").write(payload)

data_kb = os.path.getsize(os.path.join(MP, "data.js")) / 1024
total = img_bytes / 1024 + data_kb
print(f"images: {img_bytes/1024:.0f} KB ({sum(1 for x in dishes if x['img'])} photos), data.js: {data_kb:.0f} KB")
print(f"bundle payload ≈ {total:.0f} KB (main package limit 2048 KB, leave ~150 KB for code)")
if total > 1850:
    sys.exit("TOO BIG: lower MAX_EDGE/JPEG_Q in this script")
